//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 01:47:04 下午 CST 
//


package com.hotent.bpmx.plugin.core.task.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="approve"/>
 *     &lt;enumeration value="back"/>
 *     &lt;enumeration value="backToStart"/>
 *     &lt;enumeration value="recover"/>
 *     &lt;enumeration value="commu"/>
 *     &lt;enumeration value="trans"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionType")
@XmlEnum
public enum ActionType {


    /**
     * 审批
     * 
     */
    @XmlEnumValue("approve")
    APPROVE("approve"),

    /**
     * 驳回
     * 
     */
    @XmlEnumValue("back")
    BACK("back"),

    /**
     * 驳回至发起人
     * 
     */
    @XmlEnumValue("backToStart")
    BACK_TO_START("backToStart"),

    /**
     * 撤销
     * 
     */
    @XmlEnumValue("recover")
    RECOVER("recover"),

    /**
     * 沟通
     * 
     */
    @XmlEnumValue("commu")
    COMMU("commu"),

    /**
     * 任务流转
     * 
     */
    @XmlEnumValue("trans")
    TRANS("trans"),

    /**
     * 其他
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionType fromValue(String v) {
        for (ActionType c: ActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
