//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotent.bpmx.core.defxml.entity.ext package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Definitions_QNAME = new QName("http://www.jee-soft.cn/bpm", "definitions");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotent.bpmx.core.defxml.entity.ext
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtProcess.BoList }
     * 
     */
    public ExtProcess.BoList createExtProcessBoList() {
        return new ExtProcess.BoList();
    }

    /**
     * Create an instance of {@link VariableDef }
     * 
     */
    public VariableDef createVariableDef() {
        return new VariableDef();
    }

    /**
     * Create an instance of {@link ExtProcess.ExtNodes }
     * 
     */
    public ExtProcess.ExtNodes createExtProcessExtNodes() {
        return new ExtProcess.ExtNodes();
    }

    /**
     * Create an instance of {@link ButtonDef }
     * 
     */
    public ButtonDef createButtonDef() {
        return new ButtonDef();
    }

    /**
     * Create an instance of {@link TransformRule }
     * 
     */
    public TransformRule createTransformRule() {
        return new TransformRule();
    }

    /**
     * Create an instance of {@link InitItem }
     * 
     */
    public InitItem createInitItem() {
        return new InitItem();
    }

    /**
     * Create an instance of {@link Buttons }
     * 
     */
    public Buttons createButtons() {
        return new Buttons();
    }

    /**
     * Create an instance of {@link InitItem.PrevSetting }
     * 
     */
    public InitItem.PrevSetting createInitItemPrevSetting() {
        return new InitItem.PrevSetting();
    }

    /**
     * Create an instance of {@link ExtProcess.InstForm }
     * 
     */
    public ExtProcess.InstForm createExtProcessInstForm() {
        return new ExtProcess.InstForm();
    }

    /**
     * Create an instance of {@link SignNode.SignSetting }
     * 
     */
    public SignNode.SignSetting createSignNodeSignSetting() {
        return new SignNode.SignSetting();
    }

    /**
     * Create an instance of {@link ExtDefinitions }
     * 
     */
    public ExtDefinitions createExtDefinitions() {
        return new ExtDefinitions();
    }

    /**
     * Create an instance of {@link Scripts }
     * 
     */
    public Scripts createScripts() {
        return new Scripts();
    }

    /**
     * Create an instance of {@link RightsItem }
     * 
     */
    public RightsItem createRightsItem() {
        return new RightsItem();
    }

    /**
     * Create an instance of {@link FieldSetting }
     * 
     */
    public FieldSetting createFieldSetting() {
        return new FieldSetting();
    }

    /**
     * Create an instance of {@link SignNode.SignSetting.Privilege.Item }
     * 
     */
    public SignNode.SignSetting.Privilege.Item createSignNodeSignSettingPrivilegeItem() {
        return new SignNode.SignSetting.Privilege.Item();
    }

    /**
     * Create an instance of {@link VarDefs }
     * 
     */
    public VarDefs createVarDefs() {
        return new VarDefs();
    }

    /**
     * Create an instance of {@link SubProcessForm }
     * 
     */
    public SubProcessForm createSubProcessForm() {
        return new SubProcessForm();
    }

    /**
     * Create an instance of {@link SignNode.SignSetting.Privilege }
     * 
     */
    public SignNode.SignSetting.Privilege createSignNodeSignSettingPrivilege() {
        return new SignNode.SignSetting.Privilege();
    }

    /**
     * Create an instance of {@link ExtProperty }
     * 
     */
    public ExtProperty createExtProperty() {
        return new ExtProperty();
    }

    /**
     * Create an instance of {@link BaseNode }
     * 
     */
    public BaseNode createBaseNode() {
        return new BaseNode();
    }

    /**
     * Create an instance of {@link SignNode.SignSetting.SignRule }
     * 
     */
    public SignNode.SignSetting.SignRule createSignNodeSignSettingSignRule() {
        return new SignNode.SignSetting.SignRule();
    }

    /**
     * Create an instance of {@link PropItem }
     * 
     */
    public PropItem createPropItem() {
        return new PropItem();
    }

    /**
     * Create an instance of {@link UserNode }
     * 
     */
    public UserNode createUserNode() {
        return new UserNode();
    }

    /**
     * Create an instance of {@link MobileForm }
     * 
     */
    public MobileForm createMobileForm() {
        return new MobileForm();
    }

    /**
     * Create an instance of {@link FormExt }
     * 
     */
    public FormExt createFormExt() {
        return new FormExt();
    }

    /**
     * Create an instance of {@link SubTableRights }
     * 
     */
    public SubTableRights createSubTableRights() {
        return new SubTableRights();
    }

    /**
     * Create an instance of {@link ExtProperties }
     * 
     */
    public ExtProperties createExtProperties() {
        return new ExtProperties();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link TransformRules }
     * 
     */
    public TransformRules createTransformRules() {
        return new TransformRules();
    }

    /**
     * Create an instance of {@link ExtProcess.GlobalForm }
     * 
     */
    public ExtProcess.GlobalForm createExtProcessGlobalForm() {
        return new ExtProcess.GlobalForm();
    }

    /**
     * Create an instance of {@link ExtPlugins }
     * 
     */
    public ExtPlugins createExtPlugins() {
        return new ExtPlugins();
    }

    /**
     * Create an instance of {@link SignNode }
     * 
     */
    public SignNode createSignNode() {
        return new SignNode();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link InitItem.SaveSetting }
     * 
     */
    public InitItem.SaveSetting createInitItemSaveSetting() {
        return new InitItem.SaveSetting();
    }

    /**
     * Create an instance of {@link ExtProcess }
     * 
     */
    public ExtProcess createExtProcess() {
        return new ExtProcess();
    }

    /**
     * Create an instance of {@link BoDef }
     * 
     */
    public BoDef createBoDef() {
        return new BoDef();
    }

    /**
     * Create an instance of {@link FormInitSetting }
     * 
     */
    public FormInitSetting createFormInitSetting() {
        return new FormInitSetting();
    }

    /**
     * Create an instance of {@link Propers }
     * 
     */
    public Propers createPropers() {
        return new Propers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.jee-soft.cn/bpm", name = "definitions")
    public JAXBElement<ExtDefinitions> createDefinitions(ExtDefinitions value) {
        return new JAXBElement<ExtDefinitions>(_Definitions_QNAME, ExtDefinitions.class, null, value);
    }

}
