//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subRightType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="subRightType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="curUser"/>
 *     &lt;enumeration value="curOrg"/>
 *     &lt;enumeration value="script"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "subRightType")
@XmlEnum
public enum SubRightType {

    @XmlEnumValue("curUser")
    CUR_USER("curUser"),
    @XmlEnumValue("curOrg")
    CUR_ORG("curOrg"),
    @XmlEnumValue("script")
    SCRIPT("script");
    private final String value;

    SubRightType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubRightType fromValue(String v) {
        for (SubRightType c: SubRightType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
