//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.26 at 09:28:19 AM CST 
//


package com.hotent.bpmx.plugin.task.reminders.def;

import java.io.Serializable;
import java.util.List;
public class Reminder implements Serializable{
	private static final long serialVersionUID = 3527986352005255804L;
	public final static String TASK_EVENT_CREATE = "create"; // 任务创建
	public final static String TASK_EVENT_COMPLETE = "complete"; // 任务完成

	public final static String TASK_TIME_TYPE_WORKTIME = "worktime"; // 工作日
	public final static String TASK_TIME_TYPE_CALTIME = "caltime"; // 日历日

	public final static String TASK_DUE_ACTION_NO_ACTION = "no-action"; // 无动作
	public final static String TASK_DUE_ACTION_AUTO_NEXT = "auto-next"; // 自动下一个任务
	public final static String TASK_DUE_ACTION_END_PROCESS = "end-process"; // 结束任务
	public final static String TASK_DUE_ACTION_CALL_METHOD = "call-method"; // 调用方法

	//催办名称
    protected String name;
    //相对节点
    protected String relNodeId;
    //事件
    protected String relNodeEvent;
    //日期类型
    protected String dateType;
    //期限
    protected Integer dueTime;
    //到期动作
    protected String dueAction;
    //是否发送催办消息
    protected Boolean isSendMsg;
    //开始发送时间
    protected Integer msgSendTime;
    //消息数量
    protected Integer msgCount;
    //消息类型
    protected String msgType;
    //发送时间间隔
    protected Integer msgInterval;
    //催办条件
    protected String condition;
    //html消息模板
    protected String htmlMsg;
    //普通文本模板
    protected String plainMsg;
    //逾期脚本（仅仅结束动作等于脚本类型）
    protected String dueScript;
    //预警
    protected List<WarningSet> warningSetList;
    
    
    
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getRelNodeId() {
		return relNodeId;
	}
	public void setRelNodeId(String relNodeId) {
		this.relNodeId = relNodeId;
	}
	
	public String getMsgType() {
		return msgType;
	}
	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}
	public String getRelNodeEvent() {
		return relNodeEvent;
	}
	public void setRelNodeEvent(String relNodeEvent) {
		this.relNodeEvent = relNodeEvent;
	}
	public String getDateType() {
		return dateType;
	}
	public void setDateType(String dateType) {
		this.dateType = dateType;
	}
	public Integer getDueTime() {
		return dueTime;
	}
	public void setDueTime(Integer dueTime) {
		this.dueTime = dueTime;
	}
	public String getDueAction() {
		return dueAction;
	}
	public void setDueAction(String dueAction) {
		this.dueAction = dueAction;
	}
	public Boolean getIsSendMsg() {
		if(isSendMsg==null)  return false;
		return isSendMsg;
	}
	public void setIsSendMsg(Boolean isSendMsg) {
		this.isSendMsg = isSendMsg;
	}
	public Integer getMsgSendTime() {
		return msgSendTime;
	}
	public void setMsgSendTime(Integer msgSendTime) {
		this.msgSendTime = msgSendTime;
	}
	public Integer getMsgCount() {
		return msgCount;
	}
	public void setMsgCount(Integer msgCount) {
		this.msgCount = msgCount;
	}
	public Integer getMsgInterval() {
		return msgInterval;
	}
	public void setMsgInterval(Integer msgInterval) {
		this.msgInterval = msgInterval;
	}
	public String getCondition() {
		return condition;
	}
	public void setCondition(String condition) {
		this.condition = condition;
	}
	public String getHtmlMsg() {
		return htmlMsg;
	}
	public void setHtmlMsg(String htmlMsg) {
		this.htmlMsg = htmlMsg;
	}
	public String getPlainMsg() {
		return plainMsg;
	}
	public void setPlainMsg(String plainMsg) {
		this.plainMsg = plainMsg;
	}
	public String getDueScript() {
		return dueScript;
	}
	public void setDueScript(String dueScript) {
		this.dueScript = dueScript;
	}
	public List<WarningSet> getWarningSetList() {
		return warningSetList;
	}
	public void setWarningSetList(List<WarningSet> warningSetList) {
		this.warningSetList = warningSetList;
	}
}
