//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext.base;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logicCalType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="logicCalType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="or"/>
 *     &lt;enumeration value="and"/>
 *     &lt;enumeration value="exclude"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "logicCalType")
@XmlEnum
public enum LogicCalType {

    @XmlEnumValue("or")
    OR("or"),
    @XmlEnumValue("and")
    AND("and"),
    @XmlEnumValue("exclude")
    EXCLUDE("exclude");
    private final String value;

    LogicCalType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LogicCalType fromValue(String v) {
        for (LogicCalType c: LogicCalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
