//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.hotent.bpmx.core.defxml.entity.Definitions;


/**
 * <p>Java class for tDefinitions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDefinitions">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tDefinitions">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.jee-soft.cn/bpm}extProcess" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDefinitions", propOrder = {
    "extProcess"
})
public class ExtDefinitions
    extends Definitions
{

    protected ExtProcess extProcess;

    /**
     * Gets the value of the extProcess property.
     * 
     * @return
     *     possible object is
     *     {@link ExtProcess }
     *     
     */
    public ExtProcess getExtProcess() {
        return extProcess;
    }

    /**
     * Sets the value of the extProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtProcess }
     *     
     */
    public void setExtProcess(ExtProcess value) {
        this.extProcess = value;
    }

}
