//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 按钮定义
 * 
 * <p>Java class for buttonDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="buttonDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beforeScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="afterScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groovyScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="urlForm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buttonDef", propOrder = {
    "beforeScript",
    "afterScript",
    "groovyScript",
    "urlForm"
})
public class ButtonDef {

    protected String beforeScript;
    protected String afterScript;
    protected String groovyScript;
    protected String urlForm;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String alias;

    /**
     * Gets the value of the beforeScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeScript() {
        return beforeScript;
    }

    /**
     * Sets the value of the beforeScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeScript(String value) {
        this.beforeScript = value;
    }

    /**
     * Gets the value of the afterScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfterScript() {
        return afterScript;
    }

    /**
     * Sets the value of the afterScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfterScript(String value) {
        this.afterScript = value;
    }

    /**
     * Gets the value of the groovyScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroovyScript() {
        return groovyScript;
    }

    /**
     * Sets the value of the groovyScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroovyScript(String value) {
        this.groovyScript = value;
    }

    /**
     * Gets the value of the urlForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlForm() {
        return urlForm;
    }

    /**
     * Sets the value of the urlForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlForm(String value) {
        this.urlForm = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

}
