//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for form complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="form">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="parentFlowKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.jee-soft.cn/bpm}formCategory" />
 *       &lt;attribute name="formValue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "form")
@XmlSeeAlso({
    FormExt.class,
    MobileForm.class
})
public class Form {

    @XmlAttribute
    protected String parentFlowKey;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected FormCategory type;
    @XmlAttribute(required = true)
    protected String formValue;

    /**
     * Gets the value of the parentFlowKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentFlowKey() {
        return parentFlowKey;
    }

    /**
     * Sets the value of the parentFlowKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentFlowKey(String value) {
        this.parentFlowKey = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FormCategory }
     *     
     */
    public FormCategory getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormCategory }
     *     
     */
    public void setType(FormCategory value) {
        this.type = value;
    }

    /**
     * Gets the value of the formValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormValue() {
        return formValue;
    }

    /**
     * Sets the value of the formValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormValue(String value) {
        this.formValue = value;
    }

}
