//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formExt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formExt">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.jee-soft.cn/bpm}form">
 *       &lt;attribute name="prevHandler" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postHandler" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formExt")
public class FormExt
    extends Form
{

    @XmlAttribute
    protected String prevHandler;
    @XmlAttribute
    protected String postHandler;

    /**
     * Gets the value of the prevHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevHandler() {
        return prevHandler;
    }

    /**
     * Sets the value of the prevHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevHandler(String value) {
        this.prevHandler = value;
    }

    /**
     * Gets the value of the postHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostHandler() {
        return postHandler;
    }

    /**
     * Sets the value of the postHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostHandler(String value) {
        this.postHandler = value;
    }

}
