//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for initItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="initItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="prevSetting" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fieldSetting" type="{http://www.jee-soft.cn/bpm}fieldSetting" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="saveSetting" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fieldSetting" type="{http://www.jee-soft.cn/bpm}fieldSetting" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="parentDefKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "initItem", propOrder = {

})
public class InitItem {

    protected InitItem.PrevSetting prevSetting;
    protected InitItem.SaveSetting saveSetting;
    @XmlAttribute
    protected String parentDefKey;

    /**
     * Gets the value of the prevSetting property.
     * 
     * @return
     *     possible object is
     *     {@link InitItem.PrevSetting }
     *     
     */
    public InitItem.PrevSetting getPrevSetting() {
        return prevSetting;
    }

    /**
     * Sets the value of the prevSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitItem.PrevSetting }
     *     
     */
    public void setPrevSetting(InitItem.PrevSetting value) {
        this.prevSetting = value;
    }

    /**
     * Gets the value of the saveSetting property.
     * 
     * @return
     *     possible object is
     *     {@link InitItem.SaveSetting }
     *     
     */
    public InitItem.SaveSetting getSaveSetting() {
        return saveSetting;
    }

    /**
     * Sets the value of the saveSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitItem.SaveSetting }
     *     
     */
    public void setSaveSetting(InitItem.SaveSetting value) {
        this.saveSetting = value;
    }

    /**
     * Gets the value of the parentDefKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentDefKey() {
        return parentDefKey;
    }

    /**
     * Sets the value of the parentDefKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentDefKey(String value) {
        this.parentDefKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fieldSetting" type="{http://www.jee-soft.cn/bpm}fieldSetting" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldSetting"
    })
    public static class PrevSetting {

        @XmlElement(required = true)
        protected List<FieldSetting> fieldSetting;

        /**
         * Gets the value of the fieldSetting property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldSetting property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldSetting().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FieldSetting }
         * 
         * 
         */
        public List<FieldSetting> getFieldSetting() {
            if (fieldSetting == null) {
                fieldSetting = new ArrayList<FieldSetting>();
            }
            return this.fieldSetting;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fieldSetting" type="{http://www.jee-soft.cn/bpm}fieldSetting" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldSetting"
    })
    public static class SaveSetting {

        @XmlElement(required = true)
        protected List<FieldSetting> fieldSetting;

        /**
         * Gets the value of the fieldSetting property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldSetting property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldSetting().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FieldSetting }
         * 
         * 
         */
        public List<FieldSetting> getFieldSetting() {
            if (fieldSetting == null) {
                fieldSetting = new ArrayList<FieldSetting>();
            }
            return this.fieldSetting;
        }

    }

}
