//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for privilegeMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="privilegeMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="oneticket"/>
 *     &lt;enumeration value="direct"/>
 *     &lt;enumeration value="allowAddSign"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "privilegeMode")
@XmlEnum
public enum PrivilegeMode {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("oneticket")
    ONETICKET("oneticket"),
    @XmlEnumValue("direct")
    DIRECT("direct"),
    @XmlEnumValue("allowAddSign")
    ALLOW_ADD_SIGN("allowAddSign");
    private final String value;

    PrivilegeMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrivilegeMode fromValue(String v) {
        for (PrivilegeMode c: PrivilegeMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
