//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.26 at 07:21:56 下午 CST 
//


package com.hotent.bpmx.core.defxml.entity.ext.base;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for executorVar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="executorVar">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="source" use="required" type="{http://www.jee-soft.cn/bpm/plugins/userCalc/base}executorSrcType" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="executorType" use="required" type="{http://www.jee-soft.cn/bpm/plugins/userCalc/base}executorType" />
 *       &lt;attribute name="userValType" type="{http://www.jee-soft.cn/bpm/plugins/userCalc/base}userValType" />
 *       &lt;attribute name="dimension" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupValType" type="{http://www.jee-soft.cn/bpm/plugins/userCalc/base}groupValType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executorVar")
public class ExecutorVar {

    @XmlAttribute(required = true)
    protected ExecutorSrcType source;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected ExecutorType executorType;
    @XmlAttribute
    protected String userValType;
    @XmlAttribute
    protected String dimension;
    @XmlAttribute
    protected String groupValType;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutorSrcType }
     *     
     */
    public ExecutorSrcType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutorSrcType }
     *     
     */
    public void setSource(ExecutorSrcType value) {
        this.source = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the executorType property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutorType }
     *     
     */
    public ExecutorType getExecutorType() {
        return executorType;
    }

    /**
     * Sets the value of the executorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutorType }
     *     
     */
    public void setExecutorType(ExecutorType value) {
        this.executorType = value;
    }

    /**
     * Gets the value of the userValType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserValType() {
        return userValType;
    }

    /**
     * Sets the value of the userValType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserValType(String value) {
        this.userValType = value;
    }

    /**
     * Gets the value of the dimension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDimension() {
        return dimension;
    }

    /**
     * Sets the value of the dimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDimension(String value) {
        this.dimension = value;
    }

    /**
     * Gets the value of the groupValType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupValType() {
        return groupValType;
    }

    /**
     * Sets the value of the groupValType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupValType(String value) {
        this.groupValType = value;
    }

}
