//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 03:23:19 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jee-soft.cn/bpm/plugins/task/reminders", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hotent.bpmx.plugin.task.reminders.entity;
