//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 03:23:19 PM CST 
//


package com.hotent.bpmx.plugin.task.reminders.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="warnName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="warnTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "warningSet")
public class WarningSet {

    @XmlAttribute(name = "warnName")
    protected String warnName;
    @XmlAttribute(name = "warnTime")
    protected Integer warnTime;
    @XmlAttribute(name = "level")
    protected Integer level;

    /**
     * Gets the value of the warnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarnName() {
        return warnName;
    }

    /**
     * Sets the value of the warnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarnName(String value) {
        this.warnName = value;
    }

    /**
     * Gets the value of the warnTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWarnTime() {
        return warnTime;
    }

    /**
     * Sets the value of the warnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWarnTime(Integer value) {
        this.warnTime = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLevel(Integer value) {
        this.level = value;
    }

}
