//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 03:23:19 PM CST 
//


package com.hotent.bpmx.plugin.task.reminders.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="htmlMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="plainMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dueScript" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.jee-soft.cn/bpm/plugins/task/reminders}warningSet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relNodeId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relNodeEvent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dateType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dueTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dueAction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sendMsg" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="msgSendTime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="msgCount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="msgType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msgInterval" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "condition",
    "htmlMsg",
    "plainMsg",
    "dueScript",
    "warningSet"
})
@XmlRootElement(name = "reminder")
public class Reminder {

    protected String condition;
    protected String htmlMsg;
    protected String plainMsg;
    protected String dueScript;
    protected List<WarningSet> warningSet;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "relNodeId")
    protected String relNodeId;
    @XmlAttribute(name = "relNodeEvent")
    protected String relNodeEvent;
    @XmlAttribute(name = "dateType")
    protected String dateType;
    @XmlAttribute(name = "dueTime")
    protected Integer dueTime;
    @XmlAttribute(name = "dueAction")
    protected String dueAction;
    @XmlAttribute(name = "sendMsg")
    protected Boolean sendMsg;
    @XmlAttribute(name = "msgSendTime")
    protected Integer msgSendTime;
    @XmlAttribute(name = "msgCount")
    protected Integer msgCount;
    @XmlAttribute(name = "msgType")
    protected String msgType;
    @XmlAttribute(name = "msgInterval")
    protected Integer msgInterval;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the htmlMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlMsg() {
        return htmlMsg;
    }

    /**
     * Sets the value of the htmlMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlMsg(String value) {
        this.htmlMsg = value;
    }

    /**
     * Gets the value of the plainMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlainMsg() {
        return plainMsg;
    }

    /**
     * Sets the value of the plainMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlainMsg(String value) {
        this.plainMsg = value;
    }

    /**
     * Gets the value of the dueScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueScript() {
        return dueScript;
    }

    /**
     * Sets the value of the dueScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueScript(String value) {
        this.dueScript = value;
    }

    /**
     * Gets the value of the warningSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warningSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarningSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WarningSet }
     * 
     * 
     */
    public List<WarningSet> getWarningSet() {
        if (warningSet == null) {
            warningSet = new ArrayList<WarningSet>();
        }
        return this.warningSet;
    }
    
	public void setWarningSet( List<WarningSet> warningSetExtList) {
		this.warningSet = warningSetExtList;
	}

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the relNodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelNodeId() {
        return relNodeId;
    }

    /**
     * Sets the value of the relNodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelNodeId(String value) {
        this.relNodeId = value;
    }

    /**
     * Gets the value of the relNodeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelNodeEvent() {
        return relNodeEvent;
    }

    /**
     * Sets the value of the relNodeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelNodeEvent(String value) {
        this.relNodeEvent = value;
    }

    /**
     * Gets the value of the dateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * Sets the value of the dateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateType(String value) {
        this.dateType = value;
    }

    /**
     * Gets the value of the dueTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDueTime() {
        return dueTime;
    }

    /**
     * Sets the value of the dueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDueTime(Integer value) {
        this.dueTime = value;
    }

    /**
     * Gets the value of the dueAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueAction() {
        return dueAction;
    }

    /**
     * Sets the value of the dueAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueAction(String value) {
        this.dueAction = value;
    }

    /**
     * Gets the value of the sendMsg property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSendMsg() {
        return sendMsg;
    }

    /**
     * Sets the value of the sendMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSendMsg(Boolean value) {
        this.sendMsg = value;
    }

    /**
     * Gets the value of the msgSendTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMsgSendTime() {
        return msgSendTime;
    }

    /**
     * Sets the value of the msgSendTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMsgSendTime(Integer value) {
        this.msgSendTime = value;
    }

    /**
     * Gets the value of the msgCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMsgCount() {
        return msgCount;
    }

    /**
     * Sets the value of the msgCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMsgCount(Integer value) {
        this.msgCount = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the msgInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMsgInterval() {
        return msgInterval;
    }

    /**
     * Sets the value of the msgInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMsgInterval(Integer value) {
        this.msgInterval = value;
    }


}
