//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.05 at 11:41:46 上午 CST 
//


package com.hotent.bpmx.plugin.task.tasknotify.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.jee-soft.cn/bpm/plugins/task/notify}onCreate"/>
 *         &lt;element ref="{http://www.jee-soft.cn/bpm/plugins/task/notify}onComplete"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onCreate",
    "onComplete"
})
@XmlRootElement(name = "notifyForTask")
public class NotifyForTask {

    @XmlElement(required = true)
    protected OnCreate onCreate;
    @XmlElement(required = true)
    protected OnComplete onComplete;

    /**
     * Gets the value of the onCreate property.
     * 
     * @return
     *     possible object is
     *     {@link OnCreate }
     *     
     */
    public OnCreate getOnCreate() {
        return onCreate;
    }

    /**
     * Sets the value of the onCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnCreate }
     *     
     */
    public void setOnCreate(OnCreate value) {
        this.onCreate = value;
    }

    /**
     * Gets the value of the onComplete property.
     * 
     * @return
     *     possible object is
     *     {@link OnComplete }
     *     
     */
    public OnComplete getOnComplete() {
        return onComplete;
    }

    /**
     * Sets the value of the onComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnComplete }
     *     
     */
    public void setOnComplete(OnComplete value) {
        this.onComplete = value;
    }

}
