//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 03:52:27 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jee-soft.cn/bpm/plugins/execution/procNotify", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hotent.bpmx.plugin.execution.procnotify.entity;
